version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - echo $HOME
      - ./mod-downloader.py
      - find ~/.local/share/modDownloader/
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - ~/.local/share/modDownloader/mods/**/*
  discard-paths: yes
